services:
  survival:
    build: .
    container_name: minecraft-survival
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
    volumes:
      - ./survival:/minecraft